# Generated by Django 5.0.1 on 2024-01-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_restaurant_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.restaurant'),
        ),
    ]
